
github:
  use_github_app: false
  token: "gha-12345656787800"

  app_id: 0
  app_installation_id: 0
  app_private_key_filepath: ""

options:
  assign_code_reviewer_if_none_assigned: false
  show_git_output: false # Show the output from all git actions (e.g. clones, pulls and fetches)

defaults:
  git_email: "no-reply@example.com"
  git_name: "Example User"
  organisation: "github"
  code_reviewer: "no-one" # team slug
